from app.api.routes.nna import router as nna_router
from app.api.routes.adultos import router as adultos_router, adulto_penal_router
from app.api.routes.children import (
    consumo_nna_router,
    consumo_adulto_router,
    consumo_nna_item_router,
    consumo_adulto_item_router,
    disc_nna_router,
    disc_adulto_router,
    disc_nna_item_router,
    disc_adulto_item_router,
    penal_item_router,
)
from app.api.routes.ingreso import (
    causal_item_router,
    causal_router,
    derecho_item_router,
    derecho_router,
    doc_ingreso_item_router,
    doc_ingreso_router,
    ingreso_item_router,
    ingresos_router,
)
from app.api.routes.historial import (
    busqueda_item_router,
    busqueda_router,
    informe_item_router,
    informe_router,
    red_item_router,
    red_router,
)
from app.api.routes.e2p import (
    e2p_adulto_router,
    e2p_item_router,
    e2p_questions_router,
    e2p_router,
)
from app.api.routes.pmf import (
    pmf_adulto_router,
    pmf_item_router,
    pmf_router,
)
from app.api.routes.ncfas import (
    ncfas_adulto_router,
    ncfas_item_router,
    ncfas_router,
)
from app.api.routes.antecedentes import (
    entorno_item_router,
    entorno_router,
    escolar_item_router,
    escolar_router,
    familiar_item_router,
    familiar_router,
    salud_item_router,
    salud_router,
)

routers = [
    nna_router,
    adultos_router,
    adulto_penal_router,
    consumo_nna_router,
    consumo_adulto_router,
    consumo_nna_item_router,
    consumo_adulto_item_router,
    disc_nna_router,
    disc_adulto_router,
    disc_nna_item_router,
    disc_adulto_item_router,
    penal_item_router,
    ingresos_router,
    ingreso_item_router,
    causal_router,
    causal_item_router,
    derecho_router,
    derecho_item_router,
    doc_ingreso_router,
    doc_ingreso_item_router,
    red_router,
    red_item_router,
    busqueda_router,
    busqueda_item_router,
    informe_router,
    informe_item_router,
    e2p_router,
    e2p_item_router,
    pmf_router,
    pmf_item_router,
    ncfas_router,
    ncfas_item_router,
    e2p_adulto_router,
    e2p_questions_router,
    pmf_adulto_router,
    ncfas_adulto_router,
    salud_router,
    salud_item_router,
    escolar_router,
    escolar_item_router,
    familiar_router,
    familiar_item_router,
    entorno_router,
    entorno_item_router,
]
