"""add_pregunta_pmf_respuesta_pmf

Revision ID: 12d87334457e
Revises: 836702436dd6
Create Date: 2026-06-09 19:36:33.500946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12d87334457e'
down_revision: Union[str, None] = '836702436dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PreguntaPMF',
    sa.Column('id_pregunta_pmf', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('afirmacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escala', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_pregunta_pmf')
    )
    op.create_table('RespuestaPMF',
    sa.Column('id_respuesta_pmf', sa.UUID(), nullable=False),
    sa.Column('id_pmf', sa.UUID(), nullable=False),
    sa.Column('id_pregunta_pmf', sa.UUID(), nullable=False),
    sa.Column('respuesta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pmf'], ['PMF.id_pmf'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pregunta_pmf'], ['PreguntaPMF.id_pregunta_pmf'], ),
    sa.PrimaryKeyConstraint('id_respuesta_pmf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RespuestaPMF')
    op.drop_table('PreguntaPMF')
    # ### end Alembic commands ###
