"""add_url_documentacion_ingreso

Revision ID: 836702436dd6
Revises: 0b733fafb9a6
Create Date: 2026-06-07 23:02:42.831332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836702436dd6'
down_revision: Union[str, None] = '0b733fafb9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentacionIngreso', sa.Column('url_documentacion_ingreso', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DocumentacionIngreso', 'url_documentacion_ingreso')
    # ### end Alembic commands ###
