"""caso hardening: not null, composite fk, despeje por caso

Revision ID: bbf68836b0d8
Revises: 3f2e134a5977
Create Date: 2026-08-16 16:56:51.018782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf68836b0d8'
down_revision: Union[str, None] = '3f2e134a5977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLES = (
    "AntecedenteEscolar",
    "AntecedenteFamiliar",
    "AntecedenteIngreso",
    "AntecedenteSalud",
    "DocumentacionIngreso",
    "E2P",
    "InformeTribunal",
    "NCFAS",
    "PMF",
    "ProcesoDespejeFamiliar",
)


def upgrade() -> None:
    for table in _TABLES:
        op.execute(
            f"""
            UPDATE "{table}" AS r
            SET id_caso = c.id_caso
            FROM "Caso" c
            WHERE r.id_caso IS NULL
              AND c.id_nna = r.id_nna
              AND c.estado = 'En Progreso'
            """
        )
        op.alter_column(table, "id_caso", nullable=False)

# ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_caso_nna_caso', 'Caso', ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_AntecedenteEscolar_nna_caso', 'AntecedenteEscolar', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_AntecedenteFamiliar_nna_caso', 'AntecedenteFamiliar', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_AntecedenteIngreso_nna_caso', 'AntecedenteIngreso', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_AntecedenteSalud_nna_caso', 'AntecedenteSalud', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_DocumentacionIngreso_nna_caso', 'DocumentacionIngreso', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_E2P_nna_caso', 'E2P', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_InformeTribunal_nna_caso', 'InformeTribunal', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_NCFAS_nna_caso', 'NCFAS', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_PMF_nna_caso', 'PMF', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    op.drop_constraint('ProcesoDespejeFamiliar_id_nna_key', 'ProcesoDespejeFamiliar', type_='unique')
    op.create_unique_constraint('uq_despeje_nna_caso', 'ProcesoDespejeFamiliar', ['id_nna', 'id_caso'])
    op.create_foreign_key('fk_ProcesoDespejeFamiliar_nna_caso', 'ProcesoDespejeFamiliar', 'Caso', ['id_nna', 'id_caso'], ['id_nna', 'id_caso'])
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in _TABLES:
        op.alter_column(table, "id_caso", nullable=True)

    # Las 10 FK compuestas van PRIMERO: `uq_caso_nna_caso` es su destino, y
    # PostgreSQL no deja borrarlo mientras alguna lo referencie. El orden
    # original (autogenerate) borraba `uq_caso_nna_caso` en medio y fallaba con
    # "cannot drop constraint ... because other objects depend on it".
    op.drop_constraint('fk_AntecedenteEscolar_nna_caso', 'AntecedenteEscolar', type_='foreignkey')
    op.drop_constraint('fk_AntecedenteFamiliar_nna_caso', 'AntecedenteFamiliar', type_='foreignkey')
    op.drop_constraint('fk_AntecedenteIngreso_nna_caso', 'AntecedenteIngreso', type_='foreignkey')
    op.drop_constraint('fk_AntecedenteSalud_nna_caso', 'AntecedenteSalud', type_='foreignkey')
    op.drop_constraint('fk_DocumentacionIngreso_nna_caso', 'DocumentacionIngreso', type_='foreignkey')
    op.drop_constraint('fk_E2P_nna_caso', 'E2P', type_='foreignkey')
    op.drop_constraint('fk_InformeTribunal_nna_caso', 'InformeTribunal', type_='foreignkey')
    op.drop_constraint('fk_NCFAS_nna_caso', 'NCFAS', type_='foreignkey')
    op.drop_constraint('fk_PMF_nna_caso', 'PMF', type_='foreignkey')
    op.drop_constraint('fk_ProcesoDespejeFamiliar_nna_caso', 'ProcesoDespejeFamiliar', type_='foreignkey')

    op.drop_constraint('uq_caso_nna_caso', 'Caso', type_='unique')

    # Devolver el unique historico por id_nna que esta migracion reemplazo.
    op.drop_constraint('uq_despeje_nna_caso', 'ProcesoDespejeFamiliar', type_='unique')
    op.create_unique_constraint('ProcesoDespejeFamiliar_id_nna_key', 'ProcesoDespejeFamiliar', ['id_nna'], postgresql_nulls_not_distinct=False)
