"""e2p version and respuestas

Revision ID: ef7302f55ef1
Revises: 0b733fafb9a6
Create Date: 2026-05-19 20:34:45.355334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef7302f55ef1'
down_revision: Union[str, None] = '0b733fafb9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = [c["name"] for c in inspector.get_columns("E2P")]
    if "version" not in existing_cols:
        op.add_column('E2P', sa.Column('version', sa.Integer(), nullable=True))
        op.execute("UPDATE \"E2P\" SET version = 1 WHERE version IS NULL")
        op.alter_column('E2P', 'version', nullable=False)
    if "respuestas" not in existing_cols:
        op.add_column('E2P', sa.Column('respuestas', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('E2P', 'version', nullable=True)
    op.drop_column('E2P', 'respuestas')
    op.drop_column('E2P', 'version')
    # ### end Alembic commands ###
