/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthNuevoCasoRouteImport } from './routes/_auth/nuevo-caso'
import { Route as AuthNnaRouteImport } from './routes/_auth/nna'
import { Route as AuthFamiliarRouteImport } from './routes/_auth/familiar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthNnaNuevoRouteImport } from './routes/_auth/nna/nuevo'
import { Route as AuthNnaIdRouteImport } from './routes/_auth/nna/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNuevoCasoRoute = AuthNuevoCasoRouteImport.update({
  id: '/nuevo-caso',
  path: '/nuevo-caso',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNnaRoute = AuthNnaRouteImport.update({
  id: '/nna',
  path: '/nna',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFamiliarRoute = AuthFamiliarRouteImport.update({
  id: '/familiar',
  path: '/familiar',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNnaNuevoRoute = AuthNnaNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AuthNnaRoute,
} as any)
const AuthNnaIdRoute = AuthNnaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthNnaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/familiar': typeof AuthFamiliarRoute
  '/nna': typeof AuthNnaRouteWithChildren
  '/nuevo-caso': typeof AuthNuevoCasoRoute
  '/nna/$id': typeof AuthNnaIdRoute
  '/nna/nuevo': typeof AuthNnaNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/familiar': typeof AuthFamiliarRoute
  '/nna': typeof AuthNnaRouteWithChildren
  '/nuevo-caso': typeof AuthNuevoCasoRoute
  '/nna/$id': typeof AuthNnaIdRoute
  '/nna/nuevo': typeof AuthNnaNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/familiar': typeof AuthFamiliarRoute
  '/_auth/nna': typeof AuthNnaRouteWithChildren
  '/_auth/nuevo-caso': typeof AuthNuevoCasoRoute
  '/_auth/nna/$id': typeof AuthNnaIdRoute
  '/_auth/nna/nuevo': typeof AuthNnaNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/familiar'
    | '/nna'
    | '/nuevo-caso'
    | '/nna/$id'
    | '/nna/nuevo'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/familiar'
    | '/nna'
    | '/nuevo-caso'
    | '/nna/$id'
    | '/nna/nuevo'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/familiar'
    | '/_auth/nna'
    | '/_auth/nuevo-caso'
    | '/_auth/nna/$id'
    | '/_auth/nna/nuevo'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/nuevo-caso': {
      id: '/_auth/nuevo-caso'
      path: '/nuevo-caso'
      fullPath: '/nuevo-caso'
      preLoaderRoute: typeof AuthNuevoCasoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/nna': {
      id: '/_auth/nna'
      path: '/nna'
      fullPath: '/nna'
      preLoaderRoute: typeof AuthNnaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/familiar': {
      id: '/_auth/familiar'
      path: '/familiar'
      fullPath: '/familiar'
      preLoaderRoute: typeof AuthFamiliarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/nna/nuevo': {
      id: '/_auth/nna/nuevo'
      path: '/nuevo'
      fullPath: '/nna/nuevo'
      preLoaderRoute: typeof AuthNnaNuevoRouteImport
      parentRoute: typeof AuthNnaRoute
    }
    '/_auth/nna/$id': {
      id: '/_auth/nna/$id'
      path: '/$id'
      fullPath: '/nna/$id'
      preLoaderRoute: typeof AuthNnaIdRouteImport
      parentRoute: typeof AuthNnaRoute
    }
  }
}

interface AuthNnaRouteChildren {
  AuthNnaIdRoute: typeof AuthNnaIdRoute
  AuthNnaNuevoRoute: typeof AuthNnaNuevoRoute
}

const AuthNnaRouteChildren: AuthNnaRouteChildren = {
  AuthNnaIdRoute: AuthNnaIdRoute,
  AuthNnaNuevoRoute: AuthNnaNuevoRoute,
}

const AuthNnaRouteWithChildren =
  AuthNnaRoute._addFileChildren(AuthNnaRouteChildren)

interface AuthRouteChildren {
  AuthFamiliarRoute: typeof AuthFamiliarRoute
  AuthNnaRoute: typeof AuthNnaRouteWithChildren
  AuthNuevoCasoRoute: typeof AuthNuevoCasoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFamiliarRoute: AuthFamiliarRoute,
  AuthNnaRoute: AuthNnaRouteWithChildren,
  AuthNuevoCasoRoute: AuthNuevoCasoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
